# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenLibDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OpenLibDemo
  pod 'UMengAnalytics', '~> 4.1.8'
  pod 'QRCodeReaderViewController', '~> 4.0.2'
  pod 'CocoaSecurity', '~> 1.2.4'
  pod 'YCXMenu', '~> 0.0.11'
  pod 'DCPathButton', '~> 2.1.4'
  pod 'HexColors', '~> 4.0.0'
  pod 'AwesomeMenu', '~> 1.0.0'
  pod 'YLGIFImage', '~> 0.11'
  pod 'FXBlurView', '~> 1.6.4'  
  pod 'FSCalendar', '~> 2.6.0'
  target 'OpenLibDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
